#!/usr/bin/env bash
# setup-data.sh - Download and verify ePiE data archives from GitHub Releases
#
# Usage:
#   ./scripts/setup-data.sh [DATA_ROOT] [RELEASE_TAG]
#
# Arguments:
#   DATA_ROOT    - Root directory for Inputs/ and Outputs/ (default: .)
#   RELEASE_TAG  - GitHub release tag (default: v1.26.2)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

DATA_ROOT="${1:-$REPO_ROOT}"
RELEASE_TAG="${2:-v1.26.2}"
MANIFEST="$REPO_ROOT/data_manifest.json"

if [ ! -f "$MANIFEST" ]; then
  echo "ERROR: data_manifest.json not found at $MANIFEST"
  exit 1
fi

GITHUB_REPO_URL="$(git -C "$REPO_ROOT" remote get-url origin 2>/dev/null | sed 's|git@github.com:|https://github.com/|' | sed 's|\.git$||')"
if [ -z "$GITHUB_REPO_URL" ]; then
  echo "ERROR: Could not detect GitHub repo URL from git remote"
  exit 1
fi

RELEASE_URL="${GITHUB_REPO_URL}/releases/download/${RELEASE_TAG}"

require_cmd() {
  local cmd="$1"
  local help_msg="$2"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "ERROR: required command '$cmd' is not available."
    echo "       $help_msg"
    exit 1
  fi
}

install_r_dependencies() {
  if [ "${EPIE_SKIP_R_DEPS:-0}" = "1" ]; then
    echo ">>> Skipping R dependency installation (EPIE_SKIP_R_DEPS=1)"
    return 0
  fi

  if ! command -v Rscript >/dev/null 2>&1; then
    echo ">>> Rscript not found; skipping R dependency installation"
    return 0
  fi

  echo ">>> Installing R dependencies used by ePiE..."
  Rscript - <<EOF
desc_file <- file.path("$REPO_ROOT", "Package", "DESCRIPTION")
if (!file.exists(desc_file)) {
  stop("DESCRIPTION not found at: ", desc_file)
}

desc <- read.dcf(desc_file)[1, ]
parse_pkgs <- function(x) {
  if (is.null(x) || is.na(x) || !nzchar(x)) return(character())
  parts <- trimws(strsplit(x, ",")[[1]])
  pkgs <- sub("\\\\s*\\\\(.*\\\\)$", "", parts)
  pkgs[nzchar(pkgs)]
}

imports <- parse_pkgs(desc[["Imports"]])
linking <- parse_pkgs(desc[["LinkingTo"]])
required <- unique(c(imports, linking, "pkgload"))
required <- setdiff(required, c("R", "base", "methods", "utils", "stats", "graphics", "grDevices"))

installed <- rownames(installed.packages())
missing <- setdiff(required, installed)

if (length(missing) == 0) {
  cat("  [OK] All required R packages already installed\\n")
} else {
  cat("  Installing missing packages:\\n")
  cat("   -", paste(missing, collapse = ", "), "\\n")
  install.packages(missing, repos = "https://cloud.r-project.org")
}
EOF
}

echo ">>> ePiE Data Setup"
echo "    Repo root:    ${REPO_ROOT}"
echo "    Data root:    ${DATA_ROOT}"
echo "    Release tag:  ${RELEASE_TAG}"
echo "    Download URL: ${RELEASE_URL}"
echo ""

require_cmd curl "Install curl and retry."
require_cmd tar "Install tar and retry."
require_cmd shasum "Install shasum (perl-Digest-SHA) and retry."

install_r_dependencies

mkdir -p "${DATA_ROOT}/Inputs/basins" \
         "${DATA_ROOT}/Inputs/user" \
         "${DATA_ROOT}/Outputs"

verify_checksum() {
  local file="$1"
  local expected_sha256="$2"
  local actual_sha256
  actual_sha256="$(shasum -a 256 "$file" | awk '{print $1}')"
  if [ "$actual_sha256" != "$expected_sha256" ]; then
    echo "  ERROR: checksum mismatch for $(basename "$file")"
    echo "    expected: $expected_sha256"
    echo "    actual:   $actual_sha256"
    rm -f "$file"
    return 1
  fi
  echo "  Checksum OK"
}

download_archive() {
  local archive_name="$1"
  local extract_dir="$2"
  local expected_sha256="$3"

  local dest_path="${DATA_ROOT}/${extract_dir}"
  local tmp="/tmp/ePie_data_$$_${archive_name}"

  # Check if files are already present
  local archive_prefix="${archive_name%.tar.gz}"
  archive_prefix="${archive_prefix#epie_}"
  case "$archive_prefix" in
    basins_volta)    marker="${dest_path}/volta/af_riv_dry_season.shp" ;;
    basins_bega)     marker="${dest_path}/bega/bega_basin.shp" ;;
    user_data)       marker="${dest_path}/chem_Oldenkamp2018_SI.xlsx" ;;
    outputs_prebuilt) marker="${DATA_ROOT}/Outputs/volta_wet/pts.csv" ;;
    *)                marker="" ;;
  esac

  if [ -n "$marker" ] && [ -f "$marker" ]; then
    echo "  [SKIP] $(basename "$archive_name") — files already present"
    return 0
  fi

  echo "  Downloading ${archive_name}..."
  if ! curl -fSL --progress-bar -o "$tmp" "${RELEASE_URL}/${archive_name}"; then
    echo "  ERROR: failed to download ${archive_name}"
    rm -f "$tmp"
    return 1
  fi

  echo "  Verifying checksum..."
  verify_checksum "$tmp" "$expected_sha256" || return 1

  echo "  Extracting to ${dest_path}..."
  mkdir -p "$dest_path"
  tar xzf "$tmp" -C "$dest_path"
  rm -f "$tmp"

  echo "  Done."
}

echo ">>> Downloading basin and user data..."
echo ""

if command -v jq &>/dev/null; then
  # Parse archive list from the manifest. Patch releases may publish input
  # archives only; Outputs/ should then be regenerated by running scenarios.
  for archive in $(jq -r '.archives | keys[]' "$MANIFEST"); do
    sha256="$(jq -r ".archives.\"$archive\".sha256" "$MANIFEST")"
    extract_to="$(jq -r ".archives.\"$archive\".extract_to" "$MANIFEST")"
    echo "--- $archive ---"
    download_archive "$archive" "$extract_to" "$sha256" || echo "  WARNING: skipped $archive"
    echo ""
  done
else
  # Fallback: hardcode from manifest (works without jq)
  echo "--- epie_basins_volta.tar.gz ---"
  download_archive "epie_basins_volta.tar.gz" "Inputs/basins/" \
    "999d743c299ce704d0203b2685b7af9de9ce8743d72f257b614921b2bcc26ab5" || echo "  WARNING: skipped"
  echo ""
  echo "--- epie_basins_bega.tar.gz ---"
  download_archive "epie_basins_bega.tar.gz" "Inputs/basins/" \
    "5a32b6209c9a6e6be463753e62922c9f8b745a6541174693541894d6b7407919" || echo "  WARNING: skipped"
  echo ""
  echo "--- epie_user_data.tar.gz ---"
  download_archive "epie_user_data.tar.gz" "Inputs/" \
    "661f6b45da6ff2ae74aee5f8ce5dd1b83fe3ebc4492935d3cd461bd1fff712c3" || echo "  WARNING: skipped"
  echo ""
fi

echo ">>> Setup complete."
echo ""
echo "    Data directories:"
echo "      Inputs/basins/volta/   — Volta basin data"
echo "      Inputs/basins/bega/    — Bega basin data"
echo "      Inputs/user/           — Chemical properties, EEF points"
echo "      Outputs/               — Created when scenarios are run"
echo ""
echo "    Verify by running:"
echo "      Rscript scripts/smoke-test.R"
echo "      Rscript scripts/run_all_scenarios.R"
echo ""
echo "    Baseline data (not bundled) must be downloaded manually:"
echo "      HydroSHEDS  — https://www.hydrosheds.org/"
echo "      FLO1K       — https://doi.org/10.1594/PANGAEA.868758"
echo "      WorldClim   — https://www.worldclim.org/data/worldclim21.html"
echo "      GHS-POP     — https://ghsl.jrc.ec.europa.eu/ghs_pop2019.php"
echo ""
echo "    Place baseline data in Inputs/baselines/ (see docs/GETTING_STARTED.md)."
